version: "3.8"

services:
  vaultwarden:
    user: "1000"
    image: vaultwarden/server:1.30.5
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      WEBSOCKET_ENABLED: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.rileymathews.com`)
      - traefik.http.routers.vaultwarden.tls.certresolver=le
